[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./lib/morpho-blue/out/" }]
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 1000

[profile.ci]
fuzz_runs = 10_000
