name: Install repository
description: Installs repository dependencies

runs:
  using: composite

  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: stable

    - name: Install dependencies
      run: bun install --yarn --frozen-lockfile
      shell: bash
