name: Foundry

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install-cache

      - name: Build contracts
        run: bun run build:forge
        env:
          FOUNDRY_PROFILE: test

      - name: Save forge compilation cache
        uses: actions/cache/save@v4
        with:
          path: |
            cache
            out
          key: forge-${{ github.ref_name }}-${{ github.run_id }}

  test:
    needs: build

    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        type: ["slow", "fast"]
        include:
          - type: "slow"
            fuzz-runs: 1024
            max-test-rejects: 1048576
            invariant-runs: 32
            invariant-depth: 512
          - type: "fast"
            fuzz-runs: 256
            max-test-rejects: 65536
            invariant-runs: 16
            invariant-depth: 256

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/install-cache

      - name: Run tests in ${{ matrix.type }} mode
        run: bun run test:forge -vvv
        env:
          FOUNDRY_FUZZ_RUNS: ${{ matrix.fuzz-runs }}
          FOUNDRY_FUZZ_MAX_TEST_REJECTS: ${{ matrix.max-test-rejects }}
          FOUNDRY_INVARIANT_RUNS: ${{ matrix.invariant-runs }}
          FOUNDRY_INVARIANT_DEPTH: ${{ matrix.invariant-depth }}
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}
