name: Publish on NPM

on:
  workflow_dispatch:

jobs:
  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    environment:
      name: npm
      url: https://www.npmjs.com/package/@0xsend/send-earn-contracts

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
